
apiVersion: v1
kind: Service
metadata:
  name: defaultapplication
  labels:
    app: defaultapplication
spec:
  ports:
    - port: 9080
  selector:
    app: defaultapplication
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: defaultapplication
  name: defaultapplication
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: defaultapplication
    spec:
      containers:
      - image: mycluster.icp:8500/default/defaultapplication:latest
        name: defaultapplication
        ports:
        - containerPort: 9080
          protocol: TCP
